{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "SystemExit",
     "evalue": "0",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[0;31mSystemExit\u001b[0m\u001b[0;31m:\u001b[0m 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3351: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python \n",
    "import io\n",
    "import csv \n",
    "import sys\n",
    "import pandas as pd\n",
    "import geopy\n",
    "from geopy.geocoders import Nominatim\n",
    "from geopy.extra.rate_limiter import RateLimiter\n",
    "from geopy import distance \n",
    "from ipyleaflet import Map, AntPath, MeasureControl\n",
    "import ipywidgets \n",
    "import folium\n",
    "from PyQt5 import QtWidgets, QtWebEngineWidgets\n",
    "if __name__ == \"__main__\":\n",
    "    app = QtWidgets.QApplication(sys.argv)\n",
    "    \n",
    "    icd_map = folium.Map(\n",
    "    location = [30.0799,-95.4172],\n",
    "    zoom_start = 10)\n",
    "    \n",
    "    icd_group = folium.FeatureGroup(name='Intimidad con Dios Location',overlay=True)\n",
    "    brigade_group = folium.FeatureGroup(name='SWAT Brigade Locations',overlay=True)\n",
    "    abraham_group = folium.FeatureGroup(name='Abraham Groupos con Vida',overlay=True)\n",
    "    samuel_group = folium.FeatureGroup(name='Samuel Groupos con Vida',overlay=True)\n",
    "    isaac_group = folium.FeatureGroup(name='Isaac Groupos con Vida',overlay=True)\n",
    "    daniel_group = folium.FeatureGroup(name='Daniel Groupos con Vida',overlay=True)\n",
    "    israel_group = folium.FeatureGroup(name='Israel Groupos con Vida',overlay=True)\n",
    "    david_group = folium.FeatureGroup(name='David Groupos con Vida',overlay=True)\n",
    "    caleb_group = folium.FeatureGroup(name='Caleb Groupos con Vida',overlay=True)\n",
    "    josue_group = folium.FeatureGroup(name='Josue Groupos con Vida',overlay=True)\n",
    "    jose_group = folium.FeatureGroup(name='Jose Groupos con Vida',overlay=True)\n",
    "    \n",
    "    \n",
    "    brigades = pd.read_csv('AddressList1.csv')\n",
    "loc_brigade = brigades.loc[0]\n",
    "folium.Marker(\n",
    "    location = [loc_brigade['Latitude'], loc_brigade['Longitude']],\n",
    "    popup=\"Intimidad con Dios\",\n",
    "    icon = folium.Icon(color='red', icon='home', prefix='fa')\n",
    ").add_to(icd_group)\n",
    "\n",
    "for i in range(1,len(brigades)):\n",
    "    folium.Marker(\n",
    "    location = [brigades.iloc[i]['Latitude'], brigades.iloc[i]['Longitude']],\n",
    "        popup= brigades.iloc[i]['Name'],\n",
    "        tooltip =brigades.iloc[i]['Address '],\n",
    "        icon = folium.Icon(color='blue',icon='home', prefix='fa')\n",
    ").add_to(brigade_group)\n",
    "    \n",
    "\n",
    "    \n",
    "abraham = pd.read_csv('Abraham RED 3.csv')\n",
    "for i in range(0,len(abraham)):\n",
    "    folium.Marker(\n",
    "    location = [abraham.iloc[i]['Latitude'], abraham.iloc[i]['Longitude']],\n",
    "        popup= abraham.iloc[i]['Name'],\n",
    "        tooltip = abraham.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='green',icon='home', prefix='fa')\n",
    ").add_to(abraham_group)\n",
    "    \n",
    "samuel = pd.read_csv('Samuel Red.csv')\n",
    "for i in range(0,len(samuel)):\n",
    "    folium.Marker(\n",
    "    location = [samuel.iloc[i]['Latitude'], samuel.iloc[i]['Longitude']],\n",
    "        popup= samuel.iloc[i]['Name'],\n",
    "        tooltip = samuel.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='pink',icon='home', prefix='fa')\n",
    ").add_to(samuel_group)\n",
    "    \n",
    "\n",
    "isaac = pd.read_csv('Isaac Red.csv')\n",
    "for i in range(0,len(isaac)):\n",
    "    folium.Marker(\n",
    "    location = [isaac.iloc[i]['Latitude'], isaac.iloc[i]['Longitude']],\n",
    "        popup= isaac.iloc[i]['Name'],\n",
    "        tooltip = isaac.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='purple',icon='home', prefix='fa')\n",
    ").add_to(isaac_group)\n",
    "    \n",
    "daniel = pd.read_csv('Daniel Red.csv')\n",
    "for i in range(0,len(daniel)):\n",
    "    folium.Marker(\n",
    "    location = [daniel.iloc[i]['Latitude'], daniel.iloc[i]['Longitude']],\n",
    "        popup= daniel.iloc[i]['Name'],\n",
    "        tooltip = daniel.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='darkred',icon='home', prefix='fa')\n",
    ").add_to(daniel_group)\n",
    "    \n",
    "israel = pd.read_csv('Israel Red.csv')\n",
    "for i in range(0,len(israel)):\n",
    "    folium.Marker(\n",
    "    location = [israel.iloc[i]['Latitude'], israel.iloc[i]['Longitude']],\n",
    "        popup= israel.iloc[i]['Name'],\n",
    "        tooltip = israel.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='lightblue',icon='home', prefix='fa')\n",
    ").add_to(israel_group)\n",
    "    \n",
    "david = pd.read_csv('David Red.csv')\n",
    "for i in range(0,len(david)):\n",
    "    folium.Marker(\n",
    "    location = [david.iloc[i]['Latitude'], david.iloc[i]['Longitude']],\n",
    "        popup= david.iloc[i]['Name'],\n",
    "        tooltip = david.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='darkgreen',icon='home', prefix='fa')\n",
    ").add_to(david_group)\n",
    "    \n",
    "caleb = pd.read_csv('Caleb Red1.csv')\n",
    "for i in range(0,len(caleb)):\n",
    "    folium.Marker(\n",
    "    location = [caleb.iloc[i]['Latitude'], caleb.iloc[i]['Longitude']],\n",
    "        popup= caleb.iloc[i]['Name'],\n",
    "        tooltip = caleb.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='beige',icon='home', prefix='fa')\n",
    ").add_to(caleb_group)\n",
    "    \n",
    "josue = pd.read_csv('Josue Red.csv')\n",
    "for i in range(0,len(josue)):\n",
    "    folium.Marker(\n",
    "    location = [josue.iloc[i]['Latitude'], josue.iloc[i]['Longitude']],\n",
    "        popup= josue.iloc[i]['Name'],\n",
    "        tooltip = josue.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='black',icon='home', prefix='fa')\n",
    ").add_to(josue_group)\n",
    "    \n",
    "jose = pd.read_csv('Jose Red.csv')\n",
    "for i in range(0,len(jose)):\n",
    "    folium.Marker(\n",
    "    location = [jose.iloc[i]['Latitude'], jose.iloc[i]['Longitude']],\n",
    "        popup= jose.iloc[i]['Name'],\n",
    "        tooltip = jose.iloc[i]['Address'],\n",
    "        icon = folium.Icon(color='darkpurple',icon='home', prefix='fa')\n",
    ").add_to(jose_group)\n",
    "    \n",
    "\n",
    "    \n",
    "    \n",
    "icd_group.add_to(icd_map)\n",
    "brigade_group.add_to(icd_map) \n",
    "abraham_group.add_to(icd_map)\n",
    "samuel_group.add_to(icd_map)\n",
    "isaac_group.add_to(icd_map)\n",
    "daniel_group.add_to(icd_map)\n",
    "israel_group.add_to(icd_map)\n",
    "david_group.add_to(icd_map)\n",
    "caleb_group.add_to(icd_map)\n",
    "josue_group.add_to(icd_map)\n",
    "jose_group.add_to(icd_map)\n",
    "\n",
    "\n",
    "\n",
    "folium.LayerControl().add_to(icd_map) \n",
    "icd_map.add_child(brigade_group)\n",
    "icd_map.add_child(abraham_group)\n",
    "icd_map.add_child(samuel_group)\n",
    "icd_map.add_child(isaac_group)\n",
    "icd_map.add_child(daniel_group)\n",
    "icd_map.add_child(israel_group)\n",
    "icd_map.add_child(david_group)\n",
    "icd_map.add_child(caleb_group)\n",
    "icd_map.add_child(josue_group)\n",
    "icd_map.add_child(jose_group)\n",
    "\n",
    "\n",
    "data = io.BytesIO()\n",
    "icd_map.save(data, close_file=False)\n",
    "\n",
    "w = QtWebEngineWidgets.QWebEngineView()\n",
    "w.setHtml(data.getvalue().decode())\n",
    "w.resize(800, 800)\n",
    "w.show()\n",
    "\n",
    "sys.exit(app.exec_())\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
